Homework #2: View & ViewGroups
redballtoy/FavorMovie pull request #1
Opened 2020-12-29 13:40 UTC by redballtoy

2020-12-29 14:38 UTC, DmitryKolpo commented on app/src/main/java/com/example/redballtoy/favormovie/ActorsAdapter.kt
> +        fun bind(position: Int) {
Актеры хранятся не в том месте.

viewholder - это вьюшка для одного элемента. Хранить весь список актеров в каждой вьюшке нет смысла, тратится память без причин. Список всех данных хранится в адаптере и передается извне(во фрагменте/активити)
adapter.setItems(actors)
Либо пока временно можешь разово передавать всех актеров в конструкторе, без обновления. 

И в баинде адаптер берет одного конкретного актера и передает вьюхолдеру. Обо всем остальном вьюхолдеру не надо знать.
```
fun onBindViewholder(holder: ActorViewHolder, position: Int) {
    val item = items.get(position)
    holder.setItem(item)
}
```

2020-12-31 13:25 UTC, redballtoy commented on app/src/main/java/com/example/redballtoy/favormovie/ActorsAdapter.kt
> +        fun bind(position: Int) {
Спасибо за комментарии.
Поправил и запушил новый коммит

2021-01-10 09:40 UTC, DmitryKolpo commented on app/src/main/java/com/example/redballtoy/favormovie/ActorsAdapter.kt
> +        private val context: Context,
Контекст не стоит передавать извне.
В onCreateViewHolder можно брать контекст у вьюхи: parent.context, а в onBindViewHolder есть вьюха и также можно взять контекст: holder.itemView.context

2021-01-10 09:44 UTC, DmitryKolpo commented on app/src/main/java/com/example/redballtoy/favormovie/Actors.kt
> +    lateinit var actorsList: List<ActorsItem>
Зачем нужен lateinit? Вроде поле инициализируется сразу при создании, в init блоке.
В общем поле можно сделать private val. Мутабельность не нужна, публично не используется.

2021-01-10 09:45 UTC, DmitryKolpo commented on app/src/main/java/com/example/redballtoy/favormovie/Actors.kt
> +    public fun getListActors():List<ActorsItem>{
В котлине функции по умолчанию публичные, public писать не обязательно/

2021-01-10 09:53 UTC, DmitryKolpo commented on app/src/main/java/com/example/redballtoy/favormovie/MainActivity.kt
> +        val intent = Intent(this, MovieDetailsActivity::class.java)
Альтернатива: можно в MovieDetailsActivity создать метод, который возвращает интент
```
    companion object {
        fun getInstance(context: Context) = Intent(context, MovieDetailsActivity::class.java)
    }
```

И тут вызывать: val intent = MovieDetailsActivity.getInstance(this)

Плюсы:
 - отсутствует страшная ::class.java
 - если создание интента будет с параметрами и вызываться в нескольких местах, то это создание будет в одном месте: в самом MovieDetailsActivity. Будет удобно изменять.

2021-01-10 09:55 UTC, DmitryKolpo commented on app/src/main/java/com/example/redballtoy/favormovie/MovieDetailsActivity.kt
> +import androidx.recyclerview.widget.RecyclerView
Много лишних импортов. Их можно шорткатом удалять: кнтрл+аль+O или можно при коммите отметить галочку "оптимизировать импорты"
![image](https://user-images.githubusercontent.com/56305336/104119791-25619b00-5343-11eb-88b0-77d3f1895bac.png)

2021-01-10 09:57 UTC, DmitryKolpo commented on app/src/main/java/com/example/redballtoy/favormovie/MovieDetailsActivity.kt
> +    lateinit var actorsAdapter: ActorsAdapter
Поле не используется. Его нужно или удалить, или использовать.

2021-01-10 10:02 UTC, DmitryKolpo commented on app/src/main/AndroidManifest.xml
>          android:theme="@style/Theme.FavorMovie">
allowBackup лучше убрать. Чаще всего все убирают его по дефолту. Все (разработчики,qa и тд) ожидают, что если переустановить приложение, то все данные должны слететь, а этот флаг сохраняет.

Также по безопасности говорят, что сильно легче отреверсить, если этот флаг есть.

2021-01-10 10:07 UTC, DmitryKolpo commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_width="27dp"
Из-за фиксированной ширины текст Back может перенестись на следующую строку.

2021-01-10 10:09 UTC, DmitryKolpo commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_height="16dp"
Не стоит фиксировать текст по ширине, высоте. Текст очень неудачно обрежется.

2021-01-10 10:10 UTC, DmitryKolpo commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_height="16dp"
![image](https://user-images.githubusercontent.com/56305336/104120088-27c4f480-5345-11eb-8ce0-0bb54ff03aa7.png)

2021-01-10 10:15 UTC, DmitryKolpo commented on app/src/main/res/values/themes.xml
> +        <item name="android:scaleY">0.35</item>
Решение не лучшее, но оставляй как есть, потому что кастомизировать рейтинг бар - это очень неприятное занятие.

В "прод" такой код нельзя отправлять, поэтому потом надо будет заменить решение. Поставь "TODO: подглядеть у кого-нибудь готовое решение рейтинг бара"

2021-01-10 10:21 UTC, DmitryKolpo requested changes
Нужно подчистить весь код:
форматировать - ctrl + alt + L
и убрать импорты - ctrl + alt + O
убрать все строки, которые не используются
в xml убрать лишние атрибуты, например app:layout_constraintVertical_bias="0.0"

2021-01-24 11:06 UTC, DmitryKolpo approved these changes
Посмотрел изменения. Код можно еще отформатировать ctrl+alt+L, а так хорошо стало.

2021-01-25 13:51 UTC, redballtoy commented
Спасибо. Отформатирую, волью в develop и начну следующее ДЗ

2021-01-25 13:51 UTC, closed without merging